**Lab Assignment 2: Exploring linear algebra concepts with Python**

For this assignment, you may want to employ SymPy as well as/in conjunction with NumPy. SymPy is symbolic mathematics library whereas NumPy is a numerical computing library. They can do similar things, but SymPy is better for symbolic algebra and equations, whereas NumPy is better for efficient numerical calculations.

**Potential references/resources:**

Generating random numbers: https://www.w3schools.com/python/numpy/numpy_random.asp

Creating vectors and vector operations: https://www.digitalocean.com/community/tutorials/vectors-in-python

https://medium.com/@ms_somanna/guide-to-adding-noise-to-your-data-using-python-and-numpy-c8be815df524

https://www.geeksforgeeks.org/numpy-vector-multiplication/

https://www.geeksforgeeks.org/python-sympy-matrix-diagonalize-method/

https://www.geeksforgeeks.org/how-to-inverse-a-matrix-using-numpy/

https://en.wikipedia.org/wiki/SymPy

https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html

https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/

https://towardsdatascience.com/understanding-singular-value-decomposition-and-its-application-in-data-science-388a54be95d

**Remember to follow the principles of the rubric we developed:**

1. Clarity/Comments
2. Accuracy
3. Typos
4. Grammar/Syntax

**Define, in whatever method you choose, two vectors v_1 and v_2 of the same dimension and print them.**

Generating random numbers: https://www.w3schools.com/python/numpy/numpy_random.asp

Creating vectors and vector operations: https://www.digitalocean.com/community/tutorials/vectors-in-python

In [1]:
# You may choose to generate random real numbers or integers between a certain range,
# which makes sense if you decide to set a very large dimension,
# or you may choose to pick the numbers manually and created smaller vectors.

# eg. list = np.random.randint(lower_bound, upper_bound, size=dimension)

# Then you can explicit that the list of numbers you have generated is a vector
# using vector = np.array(list).


# Import necessary libraries
import numpy as np

# Define the dimensions and range of the vectors
dimension = 3
lower_bound = 0  # Lower limit for random integer generation
upper_bound = 10   # Upper limit for random integer generation

# Generate two random vectors using numpy
v1 = np.random.randint(lower_bound, upper_bound, size=dimension)
v2 = np.random.randint(lower_bound, upper_bound, size=dimension)

# Print the generated vectors
print("Vector v1:", v1)
print("Vector v2:", v2)

Vector v1: [9 6 6]
Vector v2: [4 6 0]


**Add noise to the components of v_1 and v_2. Print the outputs.**

https://medium.com/@ms_somanna/guide-to-adding-noise-to-your-data-using-python-and-numpy-c8be815df524

In [2]:
# Using Gaussian noise is likely the easiest (read about the types using the link above):
# gaussian_noise = np.random.normal(mean, std_deviation, shape)
# Make sure the shape of your noise is the same as the shape as your vectors.


mean = 0  # Mean of the noise
std_deviation = 1  # Standard deviation of the noise

# Generate Gaussian noise
noise_v1 = np.random.normal(mean, std_deviation, v1.shape)
noise_v2 = np.random.normal(mean, std_deviation, v2.shape)

# Add the noise to the vectors
v1_noisy = v1 + noise_v1
v2_noisy = v2 + noise_v2

# Print the noisy vectors
print("Noisy vector v1:", v1_noisy)
print("Noisy vector v2:", v2_noisy)

Noisy vector v1: [7.94742492 7.11961115 6.70802677]
Noisy vector v2: [1.95289106 6.04971195 1.97523212]


**Compute basic vector operations on v_1 and v_2: addition, subtraction, scalar multiplication, and the dot product. If you defined 3-dimensional vectors for v_1 and v_2 you can try to compute the cross product as well! Print the answers.**

https://www.geeksforgeeks.org/numpy-vector-multiplication/

In [3]:
# You will likely have some intuition about the code to add, subtract and perform scalar multiplication.
# The dot product is a command: np.dot(x,y)


# Addition
addition = v1 + v2

# Subtraction
subtraction = v1 - v2

# Scalar multiplication (scaling v1 by 2)
scalar_multiplication = 2 * v1

# Dot product
dot_product = np.dot(v1, v2)


# Optional: cross product
cross_product = np.cross(v1, v2)

# Print the results
print("Addition of v1 and v2:", addition)
print("Subtraction of v1 and v2:", subtraction)
print("Scalar multiplication (2 * v1):", scalar_multiplication)
print("Dot product of v1 and v2:", dot_product)
print("Cross product of v1 and v2:", cross_product)

Addition of v1 and v2: [13 12  6]
Subtraction of v1 and v2: [5 0 6]
Scalar multiplication (2 * v1): [18 12 12]
Dot product of v1 and v2: 72
Cross product of v1 and v2: [-36  24  30]


**Define a random 50x50 symmetric matrix A which is not invertible. Print the result.**

In [4]:
# Remember when a matrix is not invertible - what is the determinant?

# We will make this matrix in a specific way that is computationally efficient:
# 1. Generate a random matrix - think about how to edit the code which generated random vectors!
# 2. A nice way to quickly ensure a matrix is symmetric is by taking the average of it and its transpose.
# Why does this work? Why might it be inefficient to keep generating random matrices until we get a symmetric one?
# 3. Check the matrix generated is indeed symmetric by printing A==A.T
# Remember the properties of symmetric matrices as to why this is how we verify
# 4. Now to guarantee the matrix is not invertible, we will pad it with a row and a column of zeroes on the end:
# use np.pad(A, (0,number of rows to add), (0,number of columns to add), mode='constant', constant_values=0).
# Think about why this keeps the matrix symmetric and why it ensures we are not invertible.
# You can take the determinant of A to double check.


# Define matrix size
size = 50

# Generate a random matrix
random_matrix = np.random.randint(-10, 10, size=(size, size))

# Make the matrix symmetric by averaging it with its transpose
symmetric_matrix = (random_matrix + random_matrix.T) / 2

# Verify symmetry
is_symmetric = np.allclose(symmetric_matrix, symmetric_matrix.T)
print("Is the matrix symmetric?", is_symmetric)

# Add a row and column of zeroes to ensure the matrix is not invertible
non_invertible_matrix = np.pad(symmetric_matrix, ((0, 1), (0, 1)), mode='constant', constant_values=0)

# Calculate the determinant to confirm non-invertibility
determinant = np.linalg.det(non_invertible_matrix)
print("Determinant of the matrix:", determinant)

# Print the matrix
print("Non-invertible symmetric matrix A:")
print(non_invertible_matrix)

Is the matrix symmetric? True
Determinant of the matrix: 0.0
Non-invertible symmetric matrix A:
[[ 9.   4.5  2.  ... -1.   1.5  0. ]
 [ 4.5  5.  -4.  ... -8.   4.   0. ]
 [ 2.  -4.   1.  ... -2.5  4.5  0. ]
 ...
 [-1.  -8.  -2.5 ... -4.  -5.5  0. ]
 [ 1.5  4.   4.5 ... -5.5  9.   0. ]
 [ 0.   0.   0.  ...  0.   0.   0. ]]


**Add noise to every element in A until the determinant is non-zero. Call this matrix B, and print it. Calculate and print the determinant of B.**

In [5]:
# Recall how you added Gaussian noise to the vectors above and try to translate that to a matrix
# Define Gaussian noise parameters


mean = 0  # Mean of the noise
std_deviation = 1  # Standard deviation of the noise

# Add noise to elements in A until the determinant is non-zero
determinant_B = 0
while determinant_B == 0:
    noise_matrix = np.random.normal(mean, std_deviation, size=non_invertible_matrix.shape)
    B = non_invertible_matrix + noise_matrix
    determinant_B = np.linalg.det(B)  # Check determinant

# Print the resulting matrix B and its determinant
print("Matrix B:")
print(B)
print("Determinant of B:", determinant_B)

Matrix B:
[[ 8.91502655  5.70280964  1.16929131 ... -2.19987678  2.2060962
  -0.02054415]
 [ 4.79552065  5.2166671  -4.80453066 ... -7.43631204  4.29673452
   0.71036386]
 [ 3.20302971 -4.36425262  1.30853251 ... -1.63157837  5.21706275
   0.08545323]
 ...
 [ 0.68302951 -9.4923276  -2.90132948 ... -2.17229603 -5.12928187
   1.08985798]
 [ 2.31843529  5.51259312  4.20210564 ... -6.1326836   9.72265697
  -0.04818495]
 [-0.86455826  1.08778651 -0.93788688 ... -0.42782438  0.7776451
  -0.65550239]]
Determinant of B: -1.2198258995026897e+63


**Take the inverse of B and call it C. Print C.**

https://www.geeksforgeeks.org/how-to-inverse-a-matrix-using-numpy/


In [6]:
# You can use np.linalg.inv() to take the inverse.


# Compute the inverse of B
C = np.linalg.inv(B)

# Print the inverse matrix C
print("Inverse of matrix B (matrix C):")
print(C)

Inverse of matrix B (matrix C):
[[ 0.04595053 -0.00767988 -0.01141756 ...  0.02524108  0.01628486
   0.00927937]
 [-0.0589484   0.01266236  0.0264016  ...  0.0006944   0.00966733
   0.12342962]
 [ 0.00668896  0.08586289 -0.03262218 ...  0.01722632 -0.00405839
  -0.02626538]
 ...
 [ 0.00713428 -0.046072    0.04163906 ... -0.01620629 -0.05190337
  -0.02606461]
 [ 0.01457475 -0.03910875  0.02345636 ... -0.0369029  -0.03443357
  -0.01791685]
 [ 0.07325707 -0.36844347  0.13174855 ... -0.12393772 -0.06298853
  -0.58753485]]


**Compute BC, CB, B+C, and B^10.**

In [7]:
# Think about how to alter the code for vector addition and multiplication to fit with the matrices.


# Compute BC
BC = np.dot(B, C)

# Compute CB
CB = np.dot(C, B)

# Compute B+C
B_plus_C = B + C

# Compute B^10
B_power_10 = np.linalg.matrix_power(B, 10)

# Print the results
print("Matrix BC:")
print(BC)

print("Matrix CB:")
print(CB)

print("Matrix B + C:")
print(B_plus_C)

print("Matrix B^10:")
print(B_power_10)

Matrix BC:
[[ 1.00000000e+00 -1.43634350e-16 -1.65534319e-17 ... -3.56140240e-17
   1.46377175e-16  1.20893102e-16]
 [-5.75013309e-17  1.00000000e+00  1.51618398e-16 ...  3.09233994e-17
   8.58366556e-16 -5.47718018e-16]
 [-4.11621061e-16 -1.30373863e-15  1.00000000e+00 ...  2.56047436e-16
  -8.68944491e-16  1.64993434e-15]
 ...
 [-4.50473147e-17  2.02378156e-16  2.53964970e-16 ...  1.00000000e+00
  -1.73201420e-16  3.36341831e-16]
 [-3.99181487e-16 -5.04570321e-16 -6.62759326e-16 ...  5.94175692e-16
   1.00000000e+00 -2.40508249e-16]
 [ 1.59594560e-16 -1.11022302e-16  3.33066907e-16 ... -2.19450891e-17
   3.23930439e-16  1.00000000e+00]]
Matrix CB:
[[ 1.00000000e+00  3.86757436e-16 -1.42413309e-15 ...  1.07288600e-15
  -1.73615305e-15 -2.64790615e-16]
 [-1.39069251e-15  1.00000000e+00  1.68691177e-15 ... -7.94426129e-16
   4.29783807e-15 -7.05961673e-16]
 [-1.42665056e-16  2.13364579e-16  1.00000000e+00 ...  2.34350222e-16
  -7.90978005e-16  4.63538094e-16]
 ...
 [-5.61011883e-16 -7.4

**You likely noticed that BC and CB should give us the identity matrix, because by construction C is the inverse of B. However, the computer may not have given you exactly the identity matrix, but something very close. This does not mean your answer has wrong. Think about the natural of computation and numerics as to why this is possible!**

Write a sentence or two about what you think ...

Response: The results of 𝐵𝐶 and CB should approximate the identity matrix because C is the inverse of 𝐵. However, due to the nature of numerical computation and finite precision arithmetic, small rounding errors and approximations occur when performing matrix operations in floating-point arithmetic. These small errors run through the calculations, causing BC and CB to deviate a bit from the exact identity matrix.

**Compute and print the eigenvalues and eigenvectors of A (the original matrix).**

In [8]:
# You can use easily the command:
# eigenvalues, eigenvectors = np.linalg.eig()


# Compute eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(non_invertible_matrix)

# Print the results
print("Eigenvalues of A:")
print(eigenvalues)
print("Eigenvectors of A:")
print(eigenvectors)

Eigenvalues of A:
[ 55.96204331  51.77485178 -57.1621286   45.80408182  42.80812555
 -49.96502684 -48.04362947 -46.70753034 -44.83433454  40.20148404
  38.11120947 -40.49269365  35.28813005 -37.04010142 -35.89415114
  31.8035732  -32.29797662 -31.48710061  28.03519475  27.60641537
  25.24184966  24.73001212  21.04951581  20.30056338  19.35681445
  16.28692888  15.67868783  14.63424434  13.34403583 -27.16629162
 -25.50133801 -23.58687336 -22.882297   -20.76216579 -17.75989728
 -15.49222298 -16.02590413   6.25479418   6.70597196 -13.28614188
   4.18403598   3.05712048   1.83426517  -0.54942051  -2.29760423
  -3.9653985  -10.79229149  -5.78927396  -9.0342498   -8.23790563
   0.        ]
Eigenvectors of A:
[[-0.00312252 -0.25540086  0.10533506 ...  0.178147    0.02789643
   0.        ]
 [ 0.08084287 -0.33871339  0.02000152 ... -0.25218458 -0.16863373
   0.        ]
 [ 0.01255496  0.03726509  0.04208219 ... -0.18770375 -0.04014015
   0.        ]
 ...
 [-0.15710365  0.17433232 -0.28984535 ..

**Diagonalize A.**

For this question, SymPy has a diagonalize command which is quite easy to use. You can also use NumPy and construct the matrices P and D (where A = PDP^-1) using the calculated eigenvectors and eigenvalues. **Print D.**

https://www.geeksforgeeks.org/python-sympy-matrix-diagonalize-method/

In [9]:
# If using SymPy, import sympy as sp
# Convert the NumPy array to a SymPy matrix using sp.Matrix()
# The command P, D = matrix.diagonalize() generates P and D in A = PDP^-1.
# Remember that D is the diagonalized matrix - ie, what we are after in this question
# I like to convert back to a NumPy array to print D, because it displays nicer than the SymPy matrix
# Use np.array() to convert back if you choose to


# Import SymPy
import sympy as sp

# Convert the NumPy array to a SymPy matrix
A_sympy = sp.Matrix(non_invertible_matrix)

# Diagonalize A
P, D = A_sympy.diagonalize()

# Convert the diagonalized matrix D back to a NumPy array
D_numpy = np.array(D).astype(np.float64)

# Print the diagonalized matrix D
print("Diagonalized matrix D:")
print(D_numpy)

Diagonalized matrix D:
[[-57.1621286    0.           0.         ...   0.           0.
    0.        ]
 [  0.          55.96204331   0.         ...   0.           0.
    0.        ]
 [  0.           0.         -49.96502684 ...   0.           0.
    0.        ]
 ...
 [  0.           0.           0.         ...  28.03519475   0.
    0.        ]
 [  0.           0.           0.         ...   0.          31.8035732
    0.        ]
 [  0.           0.           0.         ...   0.           0.
    0.        ]]


**Do a singular value decomposition of a random 5x4 matrix.**

https://towardsdatascience.com/understanding-singular-value-decomposition-and-its-application-in-data-science-388a54be95d

https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html

https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/

In [10]:
# Recall how to generate random values for a matrix

# To perform the SVD you use this command:
# U, S, VT = np.linalg.svd(random.matrx)
# Print each of U, S, and VT
# Note you could call these anything


# Generate a random 5x4 matrix
random_matrix = np.random.randint(-10, 10, size=(5, 4))

# Perform SVD
U, S, VT = np.linalg.svd(random_matrix)

# Print the results
print("Matrix U:")
print(U)
print("Singular values (S):")
print(S)
print("Matrix VT:")
print(VT)

Matrix U:
[[-0.4439581  -0.32356829 -0.67816213  0.3083618   0.37843611]
 [ 0.12004702  0.58743387  0.12613524  0.74583427  0.26140255]
 [-0.62643865  0.11413751  0.52240009 -0.25496812  0.50659318]
 [-0.62932764  0.23041166 -0.02020277  0.17585582 -0.72077997]
 [ 0.0033547   0.69577877 -0.50087525 -0.50270292  0.11088012]]
Singular values (S):
[16.55082186 15.72195308  9.67603499  3.35631257]
Matrix VT:
[[ 0.70955723 -0.03466374 -0.40801765  0.57345318]
 [-0.51274923  0.64458118 -0.20133222  0.5301591 ]
 [ 0.133419    0.403366   -0.66520437 -0.61400194]
 [ 0.46456015  0.64854406  0.59202203 -0.11438704]]


**Multiply back together the three matrices obtained through the SVD, ie, recompose the matrix. There will be some error associated with this process. (Why?)**

In [11]:
# Use the techniques learned above to multiply the three matrices

# Recompose the matrix using SVD results
# Note: The singular values S need to be converted to a diagonal matrix
S_matrix = np.zeros((U.shape[0], VT.shape[0]))
np.fill_diagonal(S_matrix, S)
recomposed_matrix = np.dot(U, np.dot(S_matrix, VT))

# Print the recomposed matrix
print("Recomposed matrix:")
print(recomposed_matrix)

# Why is there an error?
# Response:
# The error occurs because SVD is computed using numerical approximations, which may introduce small inaccuracies
# due to the limitations of floating-point precision in computer arithmetic.

Recomposed matrix:
[[-3.00000000e+00 -5.00000000e+00  9.00000000e+00 -3.00000000e+00]
 [-2.00000000e+00  8.00000000e+00 -2.00000000e+00  5.00000000e+00]
 [-8.00000000e+00  3.00000000e+00  9.35702266e-15 -8.00000000e+00]
 [-9.00000000e+00  3.00000000e+00  4.00000000e+00 -4.00000000e+00]
 [-7.00000000e+00  4.00000000e+00 -1.52159130e-14  9.00000000e+00]]


**Subtract the 'recomposed' matrix from the original 5x4 matrix to get an error matrix. Take the Frobenius norm of the error matrix to see the error in scalar form.**

In [12]:
# You can use the code to take the Frobenius norm:
# frobenius_norm = np.linalg.norm(matrix, ord='fro')


# Compute the error matrix
error_matrix = random_matrix - recomposed_matrix

# Compute the Frobenius norm of the error matrix
frobenius_norm = np.linalg.norm(error_matrix, ord='fro')

# Print the error matrix and Frobenius norm
print("Error matrix:")
print(error_matrix)
print("Frobenius norm of the error matrix:")
print(frobenius_norm)

Error matrix:
[[-4.44089210e-16 -8.88178420e-16 -7.10542736e-15 -3.55271368e-15]
 [ 1.33226763e-15  0.00000000e+00  8.88178420e-15  6.21724894e-15]
 [ 1.77635684e-15  1.77635684e-15 -9.35702266e-15 -1.77635684e-15]
 [ 1.77635684e-15 -1.33226763e-15 -2.66453526e-15  8.88178420e-16]
 [-1.77635684e-15 -9.76996262e-15  1.52159130e-14  1.42108547e-14]]
Frobenius norm of the error matrix:
2.8728546203814266e-14
